apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: serviceapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: serviceapp
    spec:
      containers:
        - name: serviceapp 
          image: nogiboina/serviceapp:1.0
          ports:
            - name: http-port
              containerPort: 8080
